root: true
plugins:
  - '@typescript-eslint'
  - jest
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  sourceType: module
  ecmaVersion: 2018
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
overrides:
  - files: '**.spec.{ts,tsx}'
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
    rules:
      'jest/consistent-test-it':
        - error
        - fn: it
      'jest/require-top-level-describe': error
rules:
  '@typescript-eslint/no-misused-promises':
    - error
    - checksVoidReturn:
        attributes: false

settings:
  react:
    version: detect
